### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by joaoKuchnir** [L4ki/Azure-Plasma-Themes#1]
hello, would it be possible to add the php storm icon in Azure-Glassy-Dark-Icons ?

![image](https://github.com/user-attachments/assets/9e68c5ff-ac5c-4ea6-ae7c-96bcac2c4d87)

**Comment by L4ki** [comment]
Hi Joao,

Of course. During the next week.  I have some obligations these days, Ok?

**Comment by joaoKuchnir** [comment]
> Hi Joao,
> 
> Of course. During the next week. I have some obligations these days, Ok?

no problem, thanks!

**Comment by L4ki** [comment]
Hi Joao,

The icons have just been updated. 

I recommend that you download them here: https://store.kde.org/p/2154036

Or update from System Settings

**Comment by joaoKuchnir** [comment]
Hello, it was perfect, thank you very much!

![image](https://github.com/user-attachments/assets/65b5530a-d043-4db3-828f-b98a43e1f0a8)
